theme: jekyll-theme-cayman
title: frwrd.io
description: supporting your digital transformation with a focus on people and culture assisted by software

navigation:
  - title: Home
    url: /index
  - title: Work
    url: /work
  - title: Blog
    url: /blog
  - title: TechTalk's
    url: /techtalks
  - title: Contact
    url: /contact
